[package]
name = "dynproof-mono"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

[profile.dev]
opt-level = 0
debug = false
incremental = false
codegen-units = 1
panic = "abort"
strip = "debuginfo"
overflow-checks = false
debug-assertions = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
incremental = false
